name: run app 

on:
   push:
    branches:
       -master 
       -main
jobs:
    run app: ubuntu-latest
    steps:
      - name: Checkout code
      uses: actions/checkout@v2
      - name: Install python
      uses: actions/setup-python@v4
      with:
      python-version: '3.12'
      - name: Install dependencies
      run: pip install pandas
      - name: Run app
      run: python app.py


   